import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';
const database=process.env.LAB_BATCH_PG_DATABASE;
const pg=database?(await import('../../node_modules/pg/lib/index.js')).default:null;
const BaseBatchLedger=database?(await import('../../dist/src/base-batch-ledger.js')).BaseBatchLedger:null;
import {Challenge} from 'mppx';
import {createKeyPairSignerFromPrivateKeyBytes,getTransactionDecoder,getTransactionEncoder,getBase58Decoder,getBase58Encoder,getCompiledTransactionMessageDecoder,createTransactionMessage,setTransactionMessageFeePayer,setTransactionMessageLifetimeUsingBlockhash,appendTransactionMessageInstructions,partiallySignTransactionMessageWithSigners,getBase64EncodedWireTransaction} from '@solana/kit';
import {prepareSolanaSession,OwnerSessionController,observeSolanaOpen,observeSolanaClose,quoteSolanaSessionRent,SOLANA_SESSION_PROGRAM,SOLANA_USDC,SOLANA_GENESIS} from '../src/owner-session.mjs';
const codecs=await import(new URL('./generated/payment-channels/accounts/channel.js',import.meta.resolve('@solana/mpp')));
const helpers=await import(new URL('./server/session/on-chain.js',import.meta.resolve('@solana/mpp')));
const payer=await createKeyPairSignerFromPrivateKeyBytes(new Uint8Array(32).fill(7)),operator=await createKeyPairSignerFromPrivateKeyBytes(new Uint8Array(32).fill(8));
const bh='11111111111111111111111111111111';
const programDataAddress=getBase58Decoder().decode(new Uint8Array(32).fill(9)),programData=Buffer.alloc(45);programData.writeUInt32LE(3);const programRaw=Buffer.concat([Buffer.from([2,0,0,0]),Buffer.from(getBase58Encoder().encode(programDataAddress))]);
function args(){const request={cap:'4000',currency:SOLANA_USDC,decimals:6,network:'mainnet',operator:operator.address,recipient:operator.address,programId:SOLANA_SESSION_PROGRAM,recentBlockhash:bh,recentSlot:'444444',minVoucherDelta:'1000'};return {wwwAuthenticate:Challenge.serialize(Challenge.from({id:'synthetic-session',realm:'merchant.example',method:'solana',intent:'session',request,expires:new Date(Date.now()+60000).toISOString()})),request:{url:'https://merchant.example/session',method:'GET',digest:'a'.repeat(64)},policy:{payer:payer.address,operator:operator.address,recipient:operator.address,programDataAddress,programDataSha256:createHash('sha256').update(programData).digest('hex'),maximumOperatorOpenLamports:'5000000',depositAtomic:'4000',maxSessionAtomic:'4000',gracePeriod:900,voucherExpiresAt:Math.floor(Date.now()/1000)+1800,salt:'42'}};}
function rpcFixture(plan){const records=new Map();let currentChannel=null;
 const token=(owner,amount)=>({owner,mint:SOLANA_USDC,uiTokenAmount:{amount:String(amount)}});
 const channel=(status,cumulative)=>({discriminator:0,version:1,bump:1,status,salt:42n,deposit:4000n,settlement:{settled:BigInt(cumulative),payoutWatermark:BigInt(cumulative)},closureStartedAt:0n,payerWithdrawnAt:0n,gracePeriod:900,distributionHash:Array(32).fill(0),payer:payer.address,payee:operator.address,authorizedSigner:payer.address,mint:SOLANA_USDC,rentPayer:operator.address,openSlot:444444n});
 const encode=c=>Buffer.from(codecs.getChannelEncoder().encode(c)).toString('base64');
 async function opened(credential){const tx=getTransactionDecoder().decode(Buffer.from(credential.payload.transaction,'base64')),signatures=await operator.signTransactions([tx]);const complete={...tx,signatures:{...tx.signatures,...signatures[0]}};const wire=Buffer.from(getTransactionEncoder().encode(complete)).toString('base64');const signature=getBase58Decoder().decode(complete.signatures[operator.address]);const message=getCompiledTransactionMessageDecoder().decode(tx.messageBytes);const preBalances=message.staticAccounts.map(()=>10000000),postBalances=[...preBalances];postBalances[0]-=4000000;records.set(signature,{slot:444445,transaction:[wire,'base64'],meta:{err:null,fee:5000,preBalances,postBalances,preTokenBalances:[token(payer.address,10000)],postTokenBalances:[token(payer.address,6000),token(plan.open.channelId,4000)]}});currentChannel=encode(channel(0,0));return signature;}
 async function closed(credential){const v=credential.payload.voucher;const settle=helpers.buildSettleAndSealInstructions({channelId:plan.open.channelId,merchantSigner:operator,programId:SOLANA_SESSION_PROGRAM,voucher:{authorizedSigner:payer.address,signed:v}});const distribute=await helpers.buildDistributeInstruction({channelState:{channelId:plan.open.channelId,payee:operator.address,payer:payer.address},mint:SOLANA_USDC,programId:SOLANA_SESSION_PROGRAM,rentPayer:operator.address,splits:[],tokenProgram:'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'});let message=createTransactionMessage({version:0});message=setTransactionMessageFeePayer(operator.address,message);message=setTransactionMessageLifetimeUsingBlockhash({blockhash:bh,lastValidBlockHeight:999999n},message);message=appendTransactionMessageInstructions([...settle.instructions,distribute],message);const tx=await partiallySignTransactionMessageWithSigners(message);const wire=getBase64EncodedWireTransaction(tx),compiled=getCompiledTransactionMessageDecoder().decode(tx.messageBytes),signature=getBase58Decoder().decode(tx.signatures[operator.address]);const cumulative=BigInt(v.data.cumulativeAmount),preBalances=compiled.staticAccounts.map(()=>10000000),postBalances=[...preBalances];postBalances[0]-=5000;records.set(signature,{slot:444446,transaction:[wire,'base64'],meta:{err:null,fee:5000,preBalances,postBalances,preTokenBalances:[token(payer.address,6000),token(plan.open.channelId,4000)],postTokenBalances:[token(payer.address,6000n+4000n-cumulative),token(operator.address,cumulative)]}});currentChannel=encode(channel(3,cumulative));return signature;}
 const rpc=async(method,params)=>{if(method==='getGenesisHash')return '5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d';if(method==='getTransaction')return structuredClone(records.get(params[0]));if(method==='getTokenAccountBalance')return {value:{decimals:6,amount:'10000'}};if(method==='getBalance')return {value:10000000};if(method==='getFeeForMessage')return {value:5000};if(method==='getAccountInfo'&&params[0]===SOLANA_SESSION_PROGRAM)return {value:{owner:'BPFLoaderUpgradeab1e11111111111111111111111',executable:true,data:[programRaw.toString('base64'),'base64']}};if(method==='getAccountInfo'&&params[0]===programDataAddress)return {value:{owner:'BPFLoaderUpgradeab1e11111111111111111111111',executable:false,data:[programData.toString('base64'),'base64']}};if(method==='getAccountInfo')return {context:{slot:444446},value:currentChannel?{owner:SOLANA_SESSION_PROGRAM,executable:false,data:[currentChannel,'base64']}:null};if(method==='getMinimumBalanceForRentExemption')return params[0]===256?2672640:2039280;throw Error('RPC method not allowed');};return {rpc,opened,closed,records,channel,encode};}
test('native session prepare is pure, unsigned, exact and preserves capped semantics',async()=>{const before=globalThis.fetch;globalThis.fetch=async()=>assert.fail('no RPC allowed');try{const p=await prepareSolanaSession(args());assert.equal(p.open.deposit,'4000');assert.equal(p.challenge.request.cap,'4000');assert.equal(p.open.payee,operator.address);assert.equal(p.open.gracePeriod,900);assert(Object.isFrozen(p.policy));assert.deepEqual(Object.values(getTransactionDecoder().decode(Buffer.from(p.open.transaction,'base64')).signatures),[null,null]);const rent=await quoteSolanaSessionRent(rpcFixture(p).rpc);assert.equal(rent.channelBytes,256);assert.equal(rent.operatorRentLamports,'4711920');assert.equal(rent.buyerRentLamports,'0');}finally{globalThis.fetch=before;}});
test('ambiguous headers, expired offers, pull mode and over-cap deposit refuse before signing',async()=>{const a=args();await assert.rejects(prepareSolanaSession({...a,wwwAuthenticate:a.wwwAuthenticate+', method="solana"'}),/ambiguous/);await assert.rejects(prepareSolanaSession({...a,policy:{...a.policy,depositAtomic:'4001'}}),/cap/);const c=Challenge.deserialize(a.wwwAuthenticate);for(const request of [{...c.request,modes:['pull']},{...c.request,splits:[{bps:1,recipient:operator.address}]},{...c.request,programId:operator.address}])await assert.rejects(prepareSolanaSession({...a,wwwAuthenticate:Challenge.serialize({...c,request})}));await assert.rejects(prepareSolanaSession({...a,wwwAuthenticate:Challenge.serialize({...c,expires:'2020-01-01T00:00:00Z'})}),/expired/);});
test('native owner lifecycle backed by PostgreSQL',{skip:!database},async t=>{assert.match(database,/^lab_batch_[a-z0-9_]+$/);const settings={database,host:process.env.LAB_BATCH_PG_HOST,port:Number(process.env.LAB_BATCH_PG_PORT??5432),user:process.env.LAB_BATCH_PG_USER??'postgres',max:8};const pool=new pg.Pool(settings),peer=new pg.Pool(settings);
 async function setup(){const plan=await prepareSolanaSession(args()),id='solana-'+randomUUID(),ledger=new BaseBatchLedger(pool,id),c=rpcFixture(plan),controller=new OwnerSessionController(ledger,plan);await controller.initialize();return {plan,id,ledger,c,controller,reopen:()=>new OwnerSessionController(new BaseBatchLedger(peer,id),plan)};}
 try{
  await t.test('actual partial open signature, native account check, three vouchers and close payout/refund',async()=>{const s=await setup();let signatures=0,messages=0,opens=0,deliveries=0,closes=0;const owner={address:payer.address,signTransactions:async(t,...r)=>{signatures++;assert(await s.ledger.get('open:sign-intent'));return payer.signTransactions(t,...r);},signMessages:async(m,...r)=>{messages++;return payer.signMessages(m,...r);}};await s.controller.signOpen(owner,s.c.rpc);assert.equal(signatures,1);let openTx;await s.controller.sendOpen(async c=>{opens++;openTx=await s.c.opened(c);return {reference:openTx};});assert.equal((await s.controller.confirmOpen(s.c.rpc)).state,'chain_confirmed');const reopened=s.reopen();await reopened.initialize();for(let i=1;i<=3;i++)assert.equal((await reopened.voucher(owner,i,'1000',async c=>{deliveries++;return {reference:s.plan.open.channelId+':'+c.payload.voucher.data.cumulativeAmount};})).state,'voucher_accepted');let closeTx;await reopened.close(3,async c=>{closes++;closeTx=await s.c.closed(c);return {reference:closeTx};});const proof=await reopened.confirmClose(s.c.rpc,closeTx);assert.equal(proof.state,'chain_confirmed',JSON.stringify(proof));assert.equal(proof.merchantAtomic,'3000');assert.equal(proof.returnedBuyerAtomic,'1000');assert.equal(proof.channelRent,'reclaim_pending');assert.equal((await s.ledger.require('progress')).state,'closed');assert.deepEqual([signatures,messages,opens,deliveries,closes],[1,3,1,3,1]);await assert.rejects(reopened.signOpen(owner,s.c.rpc));await assert.rejects(reopened.close(3,()=>assert.fail()));});
  await t.test('competing connections grant one open signature; lost response cannot resend',async()=>{const s=await setup();let calls=0;const owner={address:payer.address,signTransactions:async(t,...r)=>{calls++;return payer.signTransactions(t,...r);}};const attempts=await Promise.allSettled(Array.from({length:12},(_,i)=>(i%2?s.reopen():s.controller).signOpen(owner,s.c.rpc)));assert.equal(attempts.filter(x=>x.status==='fulfilled').length,1);assert.equal(calls,1);let sends=0,tx;assert.equal((await s.controller.sendOpen(async c=>{sends++;tx=await s.c.opened(c);throw Error('lost');})).state,'unknown');await assert.rejects(s.reopen().sendOpen(()=>assert.fail()));assert.equal((await s.reopen().confirmOpen(s.c.rpc,tx)).state,'chain_confirmed');assert.equal(sends,1);});
  await t.test('uncertain open signer remains blocked across reopening',async()=>{const s=await setup();let signs=0;const owner={address:payer.address,signTransactions:async()=>{signs++;throw Error('unknown');}};await assert.rejects(s.controller.signOpen(owner,s.c.rpc));await assert.rejects(s.reopen().signOpen(owner,s.c.rpc));assert.equal(signs,1);});
  await t.test('deployment drift, fee overflow and expired observations stop before owner signing',async()=>{for(const mode of ['deployment','fee','expired']){const s=await setup();let calls=0;const owner={address:payer.address,signTransactions:async(t,...r)=>{calls++;return payer.signTransactions(t,...r);}};const rpc=async(m,p)=>{const r=await s.c.rpc(m,p);if(m==='getAccountInfo'&&p[0]===programDataAddress&&mode==='deployment')r.value.data=[Buffer.alloc(45).toString('base64'),'base64'];if(m==='getFeeForMessage'&&mode==='fee')r.value=1000000;return r;};const real=Date.now;try{if(mode==='expired')Date.now=()=>s.plan.expiresAt;await assert.rejects(s.controller.signOpen(owner,rpc));assert.equal(calls,0);}finally{Date.now=real;}}});
  await t.test('lost voucher response blocks further signing, sending and close after restart',async()=>{const s=await setup();await s.controller.signOpen(payer,s.c.rpc);await s.controller.sendOpen(async c=>({reference:await s.c.opened(c)}));await s.controller.confirmOpen(s.c.rpc);let calls=0;const owner={address:payer.address,signMessages:async(m,...r)=>{calls++;return payer.signMessages(m,...r);}};assert.equal((await s.controller.voucher(owner,1,'1000',async()=>{throw Error('lost');})).state,'unknown');await assert.rejects(s.reopen().voucher(owner,2,'1000',()=>assert.fail()));await assert.rejects(s.reopen().close(1,()=>assert.fail()));assert.equal(calls,1);});
  await t.test('wrong chain/account/token effects or signature never establish opening',async()=>{const s=await setup(),credential=await s.controller.signOpen(payer,s.c.rpc),signature=await s.c.opened(credential);assert.equal((await observeSolanaOpen(s.c.rpc,s.plan,signature)).state,'chain_confirmed');for(const mode of ['chain','truncated-genesis','owner','debit','native','signature']){const rpc=async(m,p)=>{const r=await s.c.rpc(m,p);if(m==='getGenesisHash'&&mode==='chain')return 'devnet';if(m==='getGenesisHash'&&mode==='truncated-genesis')return '5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp';if(m==='getAccountInfo'&&mode==='owner')r.value.owner=payer.address;if(m==='getTransaction'&&mode==='debit')r.meta.postTokenBalances[0].uiTokenAmount.amount='5999';if(m==='getTransaction'&&mode==='native'){const tx=getTransactionDecoder().decode(Buffer.from(r.transaction[0],'base64')),msg=getCompiledTransactionMessageDecoder().decode(tx.messageBytes);r.meta.postBalances[msg.staticAccounts.indexOf(payer.address)]--;}return r;};const requested=mode==='signature'?getBase58Decoder().decode(new Uint8Array(64).fill(9)):signature;assert.equal((await observeSolanaOpen(rpc,s.plan,requested)).state,'unknown',mode);}});
 }finally{await Promise.all([pool.end(),peer.end()]);}
});

test('mainnet RPC genesis is full hash, distinct from CAIP-2 chain reference',()=>{
 assert.equal(SOLANA_GENESIS,'5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d');
 assert.notEqual(SOLANA_GENESIS,'5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp');
});
